name: My Life Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    
jobs:
  mint:
    runs-on: ubuntu-latest

    container:
      image: asafsamuel/mint:prod
    
    env:
      SWEET_API_KEY: ${{ secrets.SWEET_API_KEY }}
      SWEET_SECRET: ${{ secrets.SWEET_SECRET }}
      SWEET_ENV: dev
      SWEET_SUBENV: shiftleft4

    steps:
      - name: Run Mint
        run: mint -vv python:3.12-slim
        
