name: My Life Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    
jobs:
  mint:
    runs-on: ubuntu-latest

    container:
      image: asafsamuel/mint:latest
    
    env:
      SWEET_API_KEY: ${{ secrets.SWEET_API_KEY }}
      SWEET_SECRET: ${{ secrets.SWEET_SECRET }}
      SWEET_ENV: dev
      SWEET_SUBENV: shiftleft4

    steps:
      - name: Run Mint
        run: mint registry.sweet.security/operator@sha256:af88a2f6bc4664a8fd68b4a8f420b7b4f8e25362
        
