name: Build, Scan, Push

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ##################################
      # Step 1 — Build Image
      ##################################
      - name: Build image
        run: |
          docker build -t asafsamuel/workflow-test:${{ github.sha }} .

      ##################################
      # Step 2 — Run Mint on the built image
      ##################################
      - name: Mint scan
        continue-on-error: false
        uses: addnab/docker-run-action@v3
        with:
          image: asafsamuel/mint:stg
          env: |
            SWEET_API_KEY=${{ secrets.SWEET_API_KEY }}
            SWEET_SECRET=${{ secrets.SWEET_SECRET }}
            SWEET_ENV=dev
            SWEET_SUBENV=shiftleft
          options: |
            -v /var/run/docker.sock:/var/run/docker.sock
          run: |
            mint -vv asafsamuel/workflow-test:${{ github.sha }}

      ##################################
      # Step 3 — Push image
      ##################################
      - name: Push image
        run: |
          docker tag asafsamuel/workflow-test:${{ github.sha }} asafsamuel/workflow-test:latest3
          docker push asafsamuel/workflow-test:${{ github.sha }}
          docker push asafsamuel/workflow-test:latest3
