name: My Life Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    
jobs:
  mint:
    runs-on: ubuntu-latest

    container:
      image: asafsamuel/mint:new
    
    env:
      SWEET_API_KEY: ${{ secrets.SWEET_API_KEY }}
      SWEET_SECRET: ${{ secrets.SWEET_SECRET }}
      SWEET_ENV: dev
      SWEET_SUBENV: shiftleft5

    steps:
      - name: Run Mint
        run: mint -vv registry.k8s.io/ingress-nginx/controller:v1.14.1
      
